/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paintbrush;

import java.awt.Color;
import static java.awt.Color.*;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.image.ColorModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.colorchooser.AbstractColorChooserPanel;
import paintbrush.D0;

/**
 *
 * @author 09795410695
 */
public class Tela extends javax.swing.JFrame {

    int tipo = 0;
    boolean primeiro = false;
    int x0, y0;
    int valorRealSlide;
    
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSlider1 = new javax.swing.JSlider();
        painel = new javax.swing.JPanel();
        Distancia = new java.awt.Checkbox();
        Preencher = new java.awt.Checkbox();
        Diametro = new java.awt.Checkbox();
        selecionaCor = new javax.swing.JColorChooser();
        corExterna = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        corInterna = new javax.swing.JPanel();
        Volume = new java.awt.Checkbox();
        Pontos = new javax.swing.JButton();
        Retas = new javax.swing.JButton();
        Retangulo = new javax.swing.JButton();
        Circulo = new javax.swing.JButton();
        Cilindro = new javax.swing.JButton();
        Spary = new javax.swing.JButton();
        Borracha = new javax.swing.JButton();
        Area1 = new java.awt.Checkbox();
        valorSlide = new javax.swing.JSlider();
        tamanho = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel.setBackground(new java.awt.Color(255, 255, 153));
        painel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                painelMouseDragged(evt);
            }
        });
        painel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Distancia.setLabel("Distância");

        Preencher.setLabel("Preencher");

        Diametro.setLabel("Diâmetro");

        corExterna.setBackground(new java.awt.Color(0, 0, 0));
        corExterna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                corExternaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout corExternaLayout = new javax.swing.GroupLayout(corExterna);
        corExterna.setLayout(corExternaLayout);
        corExternaLayout.setHorizontalGroup(
            corExternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        corExternaLayout.setVerticalGroup(
            corExternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jLabel1.setText("Cor Externa:");

        jLabel2.setText("Cor Interna:");

        corInterna.setBackground(new java.awt.Color(255, 255, 153));
        corInterna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corInternaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                corInternaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout corInternaLayout = new javax.swing.GroupLayout(corInterna);
        corInterna.setLayout(corInternaLayout);
        corInternaLayout.setHorizontalGroup(
            corInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        corInternaLayout.setVerticalGroup(
            corInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        Volume.setLabel("Volume");

        Pontos.setText("Pontos");
        Pontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PontosActionPerformed(evt);
            }
        });

        Retas.setText("Retas");
        Retas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetasActionPerformed(evt);
            }
        });

        Retangulo.setText("Retângulo");
        Retangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetanguloActionPerformed(evt);
            }
        });

        Circulo.setText("Círculo");
        Circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CirculoActionPerformed(evt);
            }
        });

        Cilindro.setText("Cilindro");
        Cilindro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CilindroActionPerformed(evt);
            }
        });

        Spary.setText("Spray");
        Spary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SparyActionPerformed(evt);
            }
        });

        Borracha.setText("Borracha");
        Borracha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrachaActionPerformed(evt);
            }
        });

        Area1.setLabel("Área");

        valorSlide.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                valorSlideMouseDragged(evt);
            }
        });
        valorSlide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                valorSlideMouseReleased(evt);
            }
        });

        tamanho.setText("Tamanho(8)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Preencher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(corExterna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(corInterna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(Pontos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Borracha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Spary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cilindro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Circulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Retangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Retas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Diametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Area1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(valorSlide, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tamanho)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selecionaCor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pontos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Retas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Retangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Circulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cilindro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Spary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Borracha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Area1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Diametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tamanho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valorSlide, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionaCor, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corExterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corInterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Preencher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void painelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMouseClicked
        switch(this.tipo){
            case 0:
                D0 ponto = new D0(evt.getX(),evt.getY(),this.corExterna.getBackground());
                ponto.desenhar(this.painel.getGraphics());
                break;
            case 1:               
                if(!primeiro)
                {
                    x0 = evt.getX();
                    y0 = evt.getY();
                    primeiro = true;
                }
                else
                {
                    D1 reta = new D1(x0,y0,evt.getX(),evt.getY(),this.corExterna.getBackground());
                    reta.desenhar(this.painel.getGraphics());
                    if(this.Distancia.isEnabled())
                        reta.comprimento();
                    primeiro = false;
                }
                break;
            case 2:
                break;
            case 3:
                break;
            case 4:
                break;
            case 5:
                break;
            case 6:
                break;
        }
    }//GEN-LAST:event_painelMouseClicked

    private void painelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMousePressed
        switch(this.tipo){
            case 0:
                D0 ponto = new D0(evt.getX(),evt.getY(),this.corExterna.getBackground());
                ponto.desenhar(this.painel.getGraphics());
                break;
            case 1:               
                if(!primeiro)
                {
                    x0 = evt.getX();
                    y0 = evt.getY();
                    primeiro = true;
                }
                break;
            case 2:
                break;
            case 3:
                break;
            case 4:
                break;
            case 5:
                break;
            case 6:
                break;
        }
    }//GEN-LAST:event_painelMousePressed

    private void painelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMouseDragged
        switch(this.tipo){
            case 0:
                D0 ponto = new D0(evt.getX(),evt.getY(),this.corExterna.getBackground());
                ponto.desenhar(this.painel.getGraphics());
                break;
            case 1:
                break;
            case 2:
                break;
            case 3:
                break;
            case 4:
                break;
            case 5:
                break;
            case 6:
                break;
        }
    }//GEN-LAST:event_painelMouseDragged

    private void PontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PontosActionPerformed
        this.tipo = 0;
    }//GEN-LAST:event_PontosActionPerformed

    private void RetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetasActionPerformed
        this.tipo = 1;
    }//GEN-LAST:event_RetasActionPerformed

    private void RetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetanguloActionPerformed
        this.tipo = 2;
    }//GEN-LAST:event_RetanguloActionPerformed

    private void CirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CirculoActionPerformed
        this.tipo = 3;
    }//GEN-LAST:event_CirculoActionPerformed

    private void CilindroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CilindroActionPerformed
        this.tipo = 4;
    }//GEN-LAST:event_CilindroActionPerformed

    private void SparyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SparyActionPerformed
        this.tipo = 5;
    }//GEN-LAST:event_SparyActionPerformed

    private void BorrachaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrachaActionPerformed
        this.tipo = 6;
    }//GEN-LAST:event_BorrachaActionPerformed

    private void corInternaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corInternaMouseClicked
        this.corInterna.setBackground(this.selecionaCor.getColor());
    }//GEN-LAST:event_corInternaMouseClicked

    private void painelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMouseReleased
        switch(this.tipo){
            case 0:
                D0 ponto = new D0(evt.getX(),evt.getY(),this.corExterna.getBackground());
                ponto.desenhar(this.painel.getGraphics());
                break;
            case 1:                
                if(primeiro)
                {
                    int x1 = evt.getX();
                    int y1 = evt.getY();
                    if((x1 - x0) > 2 || (y1 - y0) > 2)
                    {
                        D1 reta = new D1(x0,y0,x1,y1,this.corExterna.getBackground());
                        reta.desenhar(this.painel.getGraphics());
                        if(this.Distancia.isEnabled())
                            reta.comprimento();
                    }
                    primeiro = false;
                }
                break;
            case 2:
                break;
            case 3:
                break;
            case 4:
                break;
            case 5:
                break;
            case 6:
                break;
        }
    }//GEN-LAST:event_painelMouseReleased

    private void valorSlideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valorSlideMouseReleased
        this.valorRealSlide = Math.round(this.valorSlide.getValue()/6);
        this.tamanho.setText("Tamanho("+valorRealSlide+")");
    }//GEN-LAST:event_valorSlideMouseReleased

    private void valorSlideMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valorSlideMouseDragged
        this.valorRealSlide = Math.round(this.valorSlide.getValue()/6);
        this.tamanho.setText("Tamanho("+valorRealSlide+")");
    }//GEN-LAST:event_valorSlideMouseDragged

    private void corExternaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corExternaMouseReleased
        // TODO add your handling code here:        
        this.corExterna.setBackground(this.selecionaCor.getColor());
    }//GEN-LAST:event_corExternaMouseReleased

    private void corInternaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corInternaMouseReleased
        this.corInterna.setBackground(this.selecionaCor.getColor());
    }//GEN-LAST:event_corInternaMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox Area1;
    private javax.swing.JButton Borracha;
    private javax.swing.JButton Cilindro;
    private javax.swing.JButton Circulo;
    private java.awt.Checkbox Diametro;
    private java.awt.Checkbox Distancia;
    private javax.swing.JButton Pontos;
    private java.awt.Checkbox Preencher;
    private javax.swing.JButton Retangulo;
    private javax.swing.JButton Retas;
    private javax.swing.JButton Spary;
    private java.awt.Checkbox Volume;
    private javax.swing.JPanel corExterna;
    private javax.swing.JPanel corInterna;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel painel;
    private javax.swing.JColorChooser selecionaCor;
    private javax.swing.JLabel tamanho;
    private javax.swing.JSlider valorSlide;
    // End of variables declaration//GEN-END:variables
}
